name: Build and Deploy React App
 
on:
  push:
    branches:
      - dev
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v4
 
      # Set up Node.js environment with the specified version
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
 
      # Install the project dependencies using npm ci
      - name: Install dependencies
        run: npm ci
 
        # ✅ Run test cases
      - name: Run tests
        run: npm test
 
      # Optional: Upload test coverage report (if using Jest)
      - name: Upload coverage report
        if: success() && always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
      # Build the React app for production
      - name: Build React App
        run: npm run build
 
      # Deploy both dist/ and WEB-INF/ directories to the remote server via SCP
      # - name: Deploy to Remote Server via SCP
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.TOMCAT_HOST }}
      #     username: ${{ secrets.TOMCAT_USER }}
      #     key: ${{ secrets.TOMCAT_SSH_KEY }}  # Private key from GitHub Secrets
      #     port: 22
      #     source: |
      #       ./dist/*
      #       ./WEB-INF/*
      #     target: /opt/apache-tomcat9/webapps/winfo-pulse-dev-ui/  # Updated target path
      #     overwrite: true  # Overwrite existing files